### ISSUE TITLE
Sample crash randomly

### ISSUE THREAD

**Issue by 7293hq** [Jay-Goo/RangeSeekBar#17]
Hi, nice lib. I just got this crash randomly from your sample app. It seems it occur from AppCompatActivity.onStart

>  java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to com.jaygoo.widget.RangeSeekBar$SavedState
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                     Caused by: java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to com.jaygoo.widget.RangeSeekBar$SavedState
                                                                        at com.jaygoo.widget.RangeSeekBar.onRestoreInstanceState(RangeSeekBar.java:1040)
                                                                        at android.view.View.dispatchRestoreInstanceState(View.java:15755)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
                                                                        at android.view.View.restoreHierarchyState(View.java:15733)
                                                                        at android.support.v4.app.Fragment.restoreViewState(Fragment.java:475)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1329)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
                                                                        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                                        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)

Do you have any idea how to fix it ?

**Comment by 7293hq** [comment]
I just think I just found related bug that can be reproduced:

> 12-24 20:34:37.293 26940-26940/com.jaygoo.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.jaygoo.demo, PID: 26940
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jaygoo.demo/com.jaygoo.demo.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@cf7b87e: Unmarshalling unknown type code 1120403456 at offset 712
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                  Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@cf7b87e: Unmarshalling unknown type code 1120403456 at offset 712
                                                                     at android.os.Parcel.readValue(Parcel.java:2444)
                                                                     at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
                                                                     at android.os.Parcel.readSparseArray(Parcel.java:2068)
                                                                     at android.os.Parcel.readValue(Parcel.java:2422)
                                                                     at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
                                                                     at android.os.BaseBundle.unparcel(BaseBundle.java:269)
                                                                     at android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
                                                                     at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2104)
                                                                     at android.app.Activity.onRestoreInstanceState(Activity.java:1052)
                                                                     at android.app.Activity.performRestoreInstanceState(Activity.java:1007)
                                                                     at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1175)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2639)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

If you activate [don't keep activity](https://stackoverflow.com/questions/22400859/dont-keep-activities-what-is-it-for) from developer option menu, it always crash with that error log. Maybe there's should be an improvement for onSaveInstanceState method.

**Comment by 7293hq** [comment]
Hi JinJieGu, could you merge my pull request that fix this crash ? It will be helpful if you can update the version, so I do not need to modify the source code on my local computer. Thanks
