### ISSUE TITLE
ava.lang.IllegalArgumentException: setValue() min < (preset min - offsetValue) . #min:0.0 #preset min:0.0

### ISSUE THREAD

**Issue by Lans** [Jay-Goo/RangeSeekBar#57]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.qdd/com.app.qdd.activity.MainActivity}: java.lang.IllegalArgumentException: setValue() min < (preset min - offsetValue) . #min:0.0 #preset min:0.0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalArgumentException: setValue() min < (preset min - offsetValue) . #min:0.0 #preset min:0.0
        at com.jaygoo.widget.RangeSeekBar.setValue(RangeSeekBar.java:294)
        at com.jaygoo.widget.RangeSeekBar.onRestoreInstanceState(RangeSeekBar.java:752)
        at android.view.View.dispatchRestoreInstanceState(View.java:15637)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3274)
        at android.view.View.restoreHierarchyState(View.java:15615)
        at android.support.v4.app.Fragment.restoreViewState(Fragment.java:415)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)

**Comment by sedestrian** [comment]
Getting this too when rotating device
